[build]
  publish = "frontend/build"
  command = "cd frontend && npm install && npm run build"

[build.environment]
  REACT_APP_API_URL = "https://sundevil-cafeteria-backend.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 